theme: jekyll-theme-primer

title: Get Your Brain Together Hackathons
description: Materials related to the Get Your Brain Together Neuroimage Registration Hackathons

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-seo-tag

encoding: UTF-8
