name: Schedule a tutorial
description: Describe a tutorial and request a delivery time.
title: "Tutorial: My tutorial name"
labels: ["tutorial", "event:HCK03_2024_UNC"]
assignees:
  - thewtex

body:
  - type: markdown
    attributes:
      value: |
        _Please enter a tutorial name in the title bar above this text. Format: "Tutorial: Tutorial Name"._

  - type: textarea
    attributes:
      label: Tutorial description
      description: |
        Please provide a description of your tutorial. Possible ideas include sessions designed to impart knowledge on the application needs for coordinate transformations, the mathematical principles involved, and / or the current computational standards and tools available in the open-source ecosystem.
      placeholder: |
        This tutorial will ...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Duration
      description: Length of the tutorial
      options:
        - 15 minutes
        - 30 minutes
    validations:
      required: true

  - type: textarea
    attributes:
      label: Desired time slot
      description: Request time slots in Eastern Time on Friday, July 26th, 2024
      placeholder: |
        - 9 AM
        - 10 AM
        - ...
    validations:
      required: false
